#!/usr/bin/env python3
"""Compile the complete W3C catalog into public-API tests and a coverage ledger.

Only catalog metadata and W3C OUTPUT files determine expectations. No reference
parser parses the input fixtures. Requires Python 3.12+, lxml, and moonfmt.
"""

import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import re
import subprocess
import tarfile
import tempfile
from urllib.parse import urljoin
from urllib.request import urlopen

from lxml import etree

ROOT = Path(__file__).resolve().parent.parent
ARCHIVE_URL = "https://www.w3.org/XML/Test/xmlts20130923.tar.gz"
ARCHIVE_SHA256 = "9b61db9f5dbffa545f4b8d78422167083a8568c59bd1129f94138f936cf6fc1f"
OUTPUT_FILE = ROOT / "src/w3c_conformance_test.mbt"
COVERAGE_FILE = ROOT / "scripts/w3c_coverage.json"
XML_BASE = "{http://www.w3.org/XML/1998/namespace}base"
# The 20130923 root catalog incorrectly places ht-bh.xml under namespaces/misc.
BASE_CORRECTIONS = {"eduni/namespaces/misc/": "eduni/misc/"}
KNOWN_FAILURES = {
    "rmt-e3e-13": "No unresolved-entity event after a skipped parameter entity; Reader rejects &ent2;",
}
HEADER = """// AUTO-GENERATED by scripts/generate_conformance_tests.py; do not edit.
// Source: W3C XML Conformance Test Suite 20130923 (https://www.w3.org/XML/Test/).
// Fixture copyrights belong to their respective W3C suite contributors.
// Expectations come from the catalog and official OUTPUT files.

"""


def literal(value):
    """Preserve every code point, including controls, without source newlines."""
    result = ['"']
    for char in value:
        result.append({"\\": "\\\\", '"': '\\"', '\n': '\\n', '\r': '\\r', '\t': '\\t'}.get(
            char, f"\\u{{{ord(char):x}}}" if ord(char) < 32 or ord(char) > 126 else char))
    return ''.join(result) + '"'


def fixture_text(path):
    """Keep byte-decoding tests out of a decoded String API, without recoding."""
    try:
        content = path.read_bytes().decode('utf-8')
    except UnicodeDecodeError:
        return None, "byte-decoding"
    declaration = re.match(r'\ufeff?<\?xml\s+(.*?)\?>', content, re.S)
    if declaration:
        encoding = re.search(r'''encoding\s*=\s*["']([^"']+)["']''', declaration[1])
        if encoding and re.fullmatch(r'[A-Za-z][A-Za-z0-9._-]*', encoding[1]) and encoding[1].lower() not in ('utf-8', 'utf8'):
            return None, "byte-encoding-declaration"
    return content, None


def collect(suite):
    parser = etree.XMLParser(load_dtd=True, resolve_entities=True,
                             attribute_defaults=True, no_network=True)
    tree = etree.parse(str(suite / 'xmlconf.xml'), parser)
    cases, ledger, seen = [], [], set()
    for test in tree.findall('.//TEST'):
        # Follow the catalog's explicit XML Base chain. External manifest entity
        # filenames must not change the base specified by their wrapper.
        base = ''
        for node in reversed([test, *test.iterancestors()]):
            if node.get(XML_BASE):
                base = urljoin(base, node.get(XML_BASE))
        base = BASE_CORRECTIONS.get(base, base)
        uri = urljoin(base, test.attrib['URI'])
        path = (suite / uri).resolve()
        path.relative_to(suite.resolve())
        if not path.is_file():
            raise FileNotFoundError(f"Missing W3C fixture: {uri}")
        name = test.attrib['ID']
        if name in seen:
            raise ValueError(f"Duplicate W3C ID: {name}")
        seen.add(name)
        kind = test.attrib['TYPE']
        if kind not in ('valid', 'invalid', 'not-wf', 'error'):
            raise ValueError(f'Unknown W3C classification: {kind}')
        recommendation = test.get('RECOMMENDATION', 'XML1.0')
        if recommendation not in ('XML1.0', 'XML1.0-errata2e', 'XML1.0-errata3e', 'XML1.0-errata4e', 'XML1.1', 'NS1.0', 'NS1.0-errata1e', 'NS1.1'):
            raise ValueError(f'Unknown W3C recommendation: {recommendation}')
        namespaces = test.get('NAMESPACE', 'yes') != 'no'
        entry = dict(id=name, uri=uri, type=kind, recommendation=recommendation,
                     namespaces=namespaces)
        reason = None
        if recommendation in ('XML1.1', 'NS1.1') or test.get('VERSION') == '1.1':
            reason = 'xml-1.1'
        elif test.get('EDITION') and '5' not in test.get('EDITION').split():
            reason = 'obsolete-edition'
        elif test.get('ENTITIES', 'none') != 'none':
            reason = 'external-entities'
        elif kind == 'error':
            reason = 'optional-error'
        content, encoding_reason = fixture_text(path)
        reason = reason or encoding_reason
        entry['status'] = 'excluded' if reason else 'included'
        if name in KNOWN_FAILURES:
            if reason:
                raise ValueError(f'Known failure must remain executable: {name}')
            entry['known_failure'] = KNOWN_FAILURES[name]
        if reason:
            entry['reason'] = reason
        else:
            expected = None
            if test.get('OUTPUT'):
                output_uri = urljoin(base, test.attrib['OUTPUT'])
                output_path = (suite / output_uri).resolve()
                output_path.relative_to(suite.resolve())
                expected = output_path.read_bytes().decode('utf-8')
                entry['output'] = output_uri
                # Our events expose only the DOCTYPE name, not NOTATION reports.
                # Keep the acceptance test and explicitly account for this gap.
                if '<!DOCTYPE' in expected:
                    entry['output_reason'] = 'notation-events-unavailable'
                    expected = None
            entry['assertion'] = 'reject' if kind == 'not-wf' else ('canonical-output' if expected is not None else 'accept')
            cases.append((entry, content, expected))
        ledger.append(entry)
    if not cases:
        raise ValueError('No supported W3C fixtures')
    return cases, ledger


def generate(cases):
    chunks = [HEADER]
    for entry, content, expected in cases:
        name = f"w3c/{entry['type']}/{entry['id']}"
        args = [literal(content), f"namespaces={'true' if entry['namespaces'] else 'false'}"]
        if entry['type'] == 'not-wf':
            function = 'w3c_reject'
        else:
            function = 'w3c_accept'
            if expected is not None:
                args.append(f"expected={literal(expected)}")
        skip = f"#skip({literal(entry['known_failure'])})\n" if 'known_failure' in entry else ''
        chunks.append(f"///|\n{skip}test {literal(name)} {{\n  // {entry['uri']}\n  {function}(" + ',\n    '.join(args) + ")\n}\n\n")
    return ''.join(chunks)


def coverage(ledger):
    return dict(source=ARCHIVE_URL, sha256=ARCHIVE_SHA256, catalog_entries=len(ledger),
                included=sum(e['status'] == 'included' for e in ledger),
                enabled=sum(e['status'] == 'included' and 'known_failure' not in e for e in ledger),
                known_failures={e['id']: e['known_failure'] for e in ledger if 'known_failure' in e},
                assertions=dict(sorted(Counter(e['assertion'] for e in ledger if 'assertion' in e).items())),
                exclusions=dict(sorted(Counter(e['reason'] for e in ledger if 'reason' in e).items())),
                output_exclusions=dict(sorted(Counter(e['output_reason'] for e in ledger if 'output_reason' in e).items())),
                base_corrections=BASE_CORRECTIONS, cases=ledger)


def main():
    args = argparse.ArgumentParser(description=__doc__)
    args.add_argument('--archive', type=Path, default=ROOT / '_build/w3c-suite/xmlts.tar.gz')
    args.add_argument('--download', action='store_true', help='Download the pinned archive if missing')
    args.add_argument('--check', action='store_true', help='Fail if checked-in tests or coverage differ')
    options = args.parse_args()
    if not options.archive.exists() and options.download:
        options.archive.parent.mkdir(parents=True, exist_ok=True)
        with urlopen(ARCHIVE_URL, timeout=60) as response:
            data = response.read()
        if hashlib.sha256(data).hexdigest() != ARCHIVE_SHA256:
            raise ValueError('W3C archive checksum mismatch')
        options.archive.write_bytes(data)
    if hashlib.sha256(options.archive.read_bytes()).hexdigest() != ARCHIVE_SHA256:
        raise ValueError('W3C archive checksum mismatch')
    with tempfile.TemporaryDirectory() as directory:
        with tarfile.open(options.archive) as archive:
            archive.extractall(directory, filter='data')
        cases, ledger = collect(Path(directory) / 'xmlconf')
    source = subprocess.run(['moonfmt', '-'], input=generate(cases), text=True,
                            capture_output=True, check=True).stdout
    report = json.dumps(coverage(ledger), ensure_ascii=True, indent=2) + '\n'
    for path, content in [(OUTPUT_FILE, source), (COVERAGE_FILE, report)]:
        if options.check:
            if path.read_text() != content:
                raise ValueError(f'Stale generated file: {path.relative_to(ROOT)}')
        else:
            path.write_text(content)
    print(json.dumps({k: v for k, v in coverage(ledger).items() if k != 'cases'}, indent=2))


if __name__ == '__main__':
    main()
