name: check

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install latest stable MoonBit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash -s latest
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Test conformance generator
        run: |
          python -m pip install -r scripts/requirements.txt
          python -m unittest discover -s scripts -p 'test_*.py'

      - name: moon version
        run: |
          moon version --all

      - name: moon check
        run: |
          moon update
          moon check --target all --deny-warn

      - name: moon info
        run: |
          moon info --target all
          git diff --exit-code

      - name: format diff
        run: |
          moon fmt
          git diff --exit-code

      - name: Set ulimit
        run: |
          ulimit -s 8176

      - name: moon test
        run: |
          moon test --target all --deny-warn
